// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiLibros.Modelos;

[Index("IdPersona", "IdLibro", Name = "Chat_UN", IsUnique = true)]
public partial class Chat
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("idPersona")]
    public int IdPersona { get; set; }

    [Column("idLibro")]
    public int IdLibro { get; set; }
}