// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiPersonas.Modelos;

public partial class Personas
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("username")]
    [StringLength(100)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [Column("password")]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("ciudad")]
    [StringLength(100)]
    [Unicode(false)]
    public string Ciudad { get; set; }

    [Column("codigoPostal")]
    public int? CodigoPostal { get; set; }
}